### ISSUE TITLE
Support for 2.4.4

### ISSUE THREAD

**Issue by akubaa** [tobras/wireshark_doip#3]
Right now it's not possible to use 1.1.1.0 with 2.4.4 wireshark (x64)

**Comment by McBochi** [comment]
Tried it with Wireshark 2.4.4 (x64) and it worked. However, I just imported the DoIP plugin, as UDS seems to be already included.

**Comment by tobras** [comment]
I have tested the DoIP and UDS plugins on Wireshark 2.4.4. And akubaa and McBochi are right my UDS plugin collide with the built in UDS dissector used for CAN/ISO15765.

To solve this issue - simply don't copy the uds.dll file to your system.

I will remove the UDS plugin from all future releases.
